package com.mycompany.dlvery.services;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.google.api.client.googleapis.auth.oauth2.GoogleIdToken;
import com.mycompany.dlvery.datalayer.agentAuthenticationQueries;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.PreparedStatement;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 *
 * @author atulv
 */
public class getAgentDashboard extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    agentAuthenticationQueries authentication;

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        //To change body of generated methods, choose Tools | Templates.
        HttpSession session = request.getSession(true);
        if (session.getAttribute("id") != null) {
            request.setAttribute("filterBy", "TODAY");
            request.getServletContext().getRequestDispatcher("/agent/agentDashboardForDelivery.jsp").forward(request, response);
        }
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html");
        HttpSession session = request.getSession(true);

        //If the session does not exist
        if (session.getAttribute("id") == null) {
            try {

                //Auth token generated by the server 
                String idToken = request.getParameter("id_token");

                //ID generated via google
                String id = request.getParameter("id");

                // Will throw an error if the token is invalid
                GoogleIdToken.Payload payLoad = IdTokenVerifierAndParser.getPayload(idToken);
                String name = (String) payLoad.get("name");
                String email = payLoad.getEmail();

                //If the agent does not exist
                if (!authentication.doesAgentExist(id)) {
                    authentication.createAgent(name, email, id);
                    request.getServletContext().getRequestDispatcher("/agent/agentPendingAuthorization.jsp").forward(request, response);
                    return;

                }
                if (!authentication.isAgentAuthorized(id)) {
                    request.getServletContext().getRequestDispatcher("/agent/agentPendingAuthorization.jsp").forward(request, response);

                }
                int agentId = agentAuthenticationQueries.getAgentID(id);

                System.out.println("recieeved Agnet id" + agentId);

                session.setAttribute("userName", name);
                session.setAttribute("id", agentId);
                request.setAttribute("filterBy", "TODAY");
                request.getServletContext()
                        .getRequestDispatcher("/agent/agentDashboardForDelivery.jsp").forward(request, response);

            } catch (Exception e) {
                throw new RuntimeException(e);
            }

        } else {
            // The session is set and the request is a filter request and set the correct filter setting
            System.out.println(request.getParameter("filterBy"));
            request.setAttribute("filterBy", request.getParameter("filterBy"));
            request.getServletContext()
                    .getRequestDispatcher("/agent/agentDashboardForDelivery.jsp").forward(request, response);
        }
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

    @Override
    public void init() throws ServletException {
        super.init(); //To change body of generated methods, choose Tools | Templates.
        authentication = new agentAuthenticationQueries();
    }

    @Override
    public void destroy() {
        super.destroy(); //To change body of generated methods, choose Tools | Templates.
        try {
            //  authentication.closeConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
